### ISSUE TITLE
Please fix the problem

### ISSUE THREAD

**Issue by RudyPao** [rotemdan/MaximizerForYouTube#13]
Please fix the problem: Can't play two videos (whether it's live stream or normal video) ; If I play two videos at the same time , one of them will stop , Thank you !

**Comment by rotemdan** [comment]
That's a feature of the script itself. It is designed to add that behavior as a feature. Since there is no options UI, you can only disable it by editing the code itself.

Change:

```js
function onWindowLoad() {
	log('onWindowLoad')

	ensureModdedTheaterModeButton()
	ensurePlayerAutoPause()
}
```
To:

```js
function onWindowLoad() {
	log('onWindowLoad')

	ensureModdedTheaterModeButton()
	//ensurePlayerAutoPause()
}
```
(basically comment out `ensurePlayerAutoPause()`)

**Comment by RudyPao** [comment]
> That's a feature of the script itself. It is designed to add that behavior as a feature. Since there is no options UI, you can only disable it by editing the code itself.
> 
> Change:
> 
> ```js
> function onWindowLoad() {
> 	log('onWindowLoad')
> 
> 	ensureModdedTheaterModeButton()
> 	ensurePlayerAutoPause()
> }
> ```
> 
> To:
> 
> ```js
> function onWindowLoad() {
> 	log('onWindowLoad')
> 
> 	ensureModdedTheaterModeButton()
> 	//ensurePlayerAutoPause()
> }
> ```
> 
> (basically comment out `ensurePlayerAutoPause()`)

f

**Comment by RudyPao** [comment]
Thanks for the answer! Nice script!
