### ISSUE TITLE
Video area showing on top of text.

### ISSUE THREAD

**Issue by lobox360** [rotemdan/MaximizerForYouTube#2]
Today I noticed a newer issue where maximized video shows on top of text area. It previously used to push the whole text area downwards so it was easy to read the description when scrolling down but now is necessary to turn off the plugin in order to be able to read so that comes really unhandy. Just giving you heads up if can fix this bug it will be much appreciated, great plugin btw, thanks.

**Comment by rotemdan** [comment]
Thanks for the report. I can see it happening both in Chrome and Firefox. Seems like YouTube has made a change in their player today that seems to have broken the script. I will try to fix it as soon as possible.
