### ISSUE TITLE
disable the "Expands the video description."???

### ISSUE THREAD

**Issue by Entropix03** [rotemdan/MaximizerForYouTube#7]
Great scrip but is there a way to disable the "Expands the video description." is there a line I can disable or delete??

**Comment by rotemdan** [comment]
Just comment [this line (click to see on GitHub)](https://github.com/rotemdan/MaximizerForYouTube/blob/dcb281d09ea775305ddc021b757bcb85e9cb95bd/MaximizerForYouTube.user.js#L343):

```ts
ensureExpandedVideoDescription();
```
->
```ts
// ensureExpandedVideoDescription();
```

I believe this should work.

**Comment by Entropix03** [comment]
Thank you seems to work :)
